const $=s=>document.querySelector(s), usersKey='nv_users', sessionKey='nv_session';let users=JSON.parse(localStorage.getItem(usersKey)||'[]');
const testUser={id:'test-account',name:'Тестовый пользователь',email:'test@nashavolna.ru',password:'Test1234!'};
if(!users.some(u=>u.email===testUser.email)){users.push(testUser);localStorage.setItem(usersKey,JSON.stringify(users));}
function showAuth(){document.querySelector('#auth').hidden=false;document.querySelector('#app').hidden=true}
function showApp(u){$('#auth').hidden=true;$('#app').hidden=false;$('#userName').textContent=u.name;$('#userEmail').textContent=u.email;$('#avatar').textContent=(u.name||'A')[0].toUpperCase();render('Главная')}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const reg=t.dataset.mode==='register';$('#loginForm').hidden=reg;$('#registerForm').hidden=!reg});
$('#registerBtn').onclick=()=>{const name=$('#regName').value.trim(),email=$('#regEmail').value.trim().toLowerCase(),password=$('#regPassword').value;if(!name||!email||password.length<6)return $('#regMsg').textContent='Заполните поля. Пароль — минимум 6 символов.';if(users.some(u=>u.email===email))return $('#regMsg').textContent='Пользователь с таким email уже существует.';const u={id:crypto.randomUUID(),name,email,password};users.push(u);localStorage.setItem(usersKey,JSON.stringify(users));localStorage.setItem(sessionKey,u.id);showApp(u)};
$('#loginBtn').onclick=()=>{const email=$('#loginEmail').value.trim().toLowerCase(),password=$('#loginPassword').value,u=users.find(x=>x.email===email&&x.password===password);if(!u)return $('#loginMsg').textContent='Неверный email или пароль.';localStorage.setItem(sessionKey,u.id);showApp(u)};
$('#logout').onclick=()=>{localStorage.removeItem(sessionKey);showAuth()};
document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{document.querySelectorAll('nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active');render(a.dataset.page)});
function render(page){const p=$('#page');if(page==='Главная'){p.innerHTML='<div class="welcome"><label>AI-ПЛАТФОРМА</label><h1>Добро пожаловать, '+$('#userName').textContent+'!</h1><p>Ваша AI-система готова к работе.</p></div><div class="stats"><article><small>Задачи</small><b>12</b><em>↑ 20% к прошлой неделе</em></article><article><small>Проекты</small><b>5</b><em>2 в активной разработке</em></article><article><small>Доход</small><b>1 250 000 ₽</b><em>↑ 12% к прошлому месяцу</em></article><article><small>Команда</small><b>8</b><em>Все в сети</em></article></div><div class="grid"><article class="panel ai"><h2>✦ AI Ассистент</h2><p>Чем я могу помочь сегодня?</p><div class="buttons"><button>＋ Создать задачу</button><button>◈ Проанализировать данные</button><button>▣ Подготовить отчёт</button><button>⌕ Найти информацию</button><button>✎ Написать письмо</button><button>⚡ Запустить автоматизацию</button></div></article><article class="panel quick"><h2>Быстрые действия</h2><button>＋ Новый проект <span>›</span></button><button>▣ Добавить документ <span>›</span></button><button>₽ Создать счёт <span>›</span></button><button>✦ Запустить AI-агента <span>›</span></button></article></div><div class="grid lower"><article class="panel"><div class="title"><h2>Активные проекты</h2><a>Все →</a></div><div class="project"><i>▣</i><div><b>Сайт для клиента</b><small>Разработка</small><div class="bar"><i style="width:70%"></i></div></div><strong>70%</strong></div><div class="project"><i>◈</i><div><b>AI-бот для продаж</b><small>Проектирование</small><div class="bar"><i style="width:45%"></i></div></div><strong>45%</strong></div></article><article class="panel"><div class="title"><h2>Последние уведомления</h2><a>Все →</a></div><div class="notice">● <b>Новый клиент</b><small>ООО «Технологии» оставил заявку · 5 мин назад</small></div><div class="notice">● <b>AI-агент</b><small>Сформирован еженедельный отчёт · 3 часа назад</small></div></article></div>'}else p.innerHTML='<div class="panel empty"><div style="font-size:40px">✦</div><h2>'+page+'</h2><p>Раздел создан в архитектуре MVP. Здесь будет полноценный рабочий модуль.</p></div>'}
const saved=localStorage.getItem('nv_theme');if(saved==='light')document.body.classList.add('light');const th=$('#theme');th.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('nv_theme',document.body.classList.contains('light')?'light':'dark');th.textContent=document.body.classList.contains('light')?'☾':'☀'};
// Auth is temporarily disabled for the public MVP. Registration/login code is preserved above for later activation.
showApp({name:'Александр',email:'demo@nashavolna.ru'});