const memories=[{title:"Ты и я",date:"09.04.2021",desc:"Наша история продолжается…",video:"videos/01.mp4",photo:"photos/IMG_0322.jpeg",hue:10},{title:"Как мы познакомились",date:"Апрель 2021",desc:"С этого всё началось.",video:"videos/02.mp4",photo:"photos/02.jpg",hue:335},{title:"Наше первое свидание",date:"2021",desc:"Волнение, улыбки, ты.",video:"videos/03.mp4",photo:"photos/03.jpg",hue:25},{title:"Зимние прогулки",date:"Зима",desc:"Ты и я, и этот снег.",video:"videos/04.mp4",photo:"photos/04.jpg",hue:205},{title:"Поездка в Питер",date:"2022",desc:"Лучшее путешествие.",video:"videos/05.mp4",photo:"photos/05.jpg",hue:285},{title:"Тот самый вечер",date:"2023",desc:"Когда всё стало по-другому.",video:"videos/06.mp4",photo:"photos/06.jpg",hue:350},{title:"Спасибо, что ты есть",date:"2024",desc:"Видео только для тебя.",video:"videos/07.mp4",photo:"photos/07.jpg",hue:40},{title:"Впереди ещё столько всего",date:"Сегодня",desc:"Это только начало…",video:"videos/08.mp4",photo:"photos/08.jpg",hue:15}];
function init(){const $=id=>document.getElementById(id),orbit=$("memoryOrbit"),mobileItems=$("mobileItems"),video=$("video"),canvas=$("waveCanvas"),hero=$("hero");if(!orbit||!mobileItems||!canvas||!hero)return;let active=-1,watched=[];try{const saved=JSON.parse(localStorage.getItem("nashaVolnaWatched")||"[]");if(Array.isArray(saved))watched=saved.filter(i=>Number.isInteger(i)&&i>=0&&i<memories.length)}catch(e){}let hue=12,targetHue=12,waveT=0,secretShown=false;
function makeImg(src,i){const img=document.createElement("img");img.src=src;img.alt="";img.onerror=()=>{img.style.background=`radial-gradient(circle at 35% 30%,hsl(${(i*43)%360} 70% 42%),hsl(${(i*43+45)%360} 45% 12%))`;img.removeAttribute("src")};return img}
function positionMemories(){const r=hero.getBoundingClientRect(),w=r.width,h=r.height,mobile=w<901,radius=mobile?Math.min(w*.38,150,h*.30):Math.min(w*.34,300,h*.34),cx=w*.5,cy=mobile?h*.49:h*.51;document.querySelectorAll(".memory").forEach((el,i)=>{const a=(-90+i*45)*Math.PI/180;el.style.left=`${cx+Math.cos(a)*radius}px`;el.style.top=`${cy+Math.sin(a)*radius}px`;el.style.setProperty("--wave-index",i)})}
function render(){orbit.innerHTML="";mobileItems.innerHTML="";memories.forEach((m,i)=>{const b=document.createElement("button");b.type="button";b.className="memory"+(watched.includes(i)?" watched":"");b.title=m.title;b.setAttribute("aria-label",`${i+1}. ${m.title}`);b.append(makeImg(m.photo,i));const n=document.createElement("span");n.className="number";n.textContent=i+1;b.append(n);if(watched.includes(i)){const d=document.createElement("span");d.className="dot";b.append(d)}b.onclick=()=>openMemory(i);orbit.append(b);const row=document.createElement("div");row.className="mobile-item";row.append(makeImg(m.photo,i));const text=document.createElement("div");text.innerHTML=`<strong>${m.title}</strong><small>${m.date} · ${m.desc}</small>`;row.append(text);if(watched.includes(i)){const c=document.createElement("span");c.className="check";c.textContent="✓";row.append(c)}row.onclick=()=>openMemory(i);mobileItems.append(row)});const count=$("countLabel");if(count)count.textContent=`${memories.length} видео`;positionMemories()}
function openMemory(i){active=i;const m=memories[i];targetHue=m.hue;$("playerTitle").textContent=m.title;$("playerDate").textContent=m.date;$("playerDescription").textContent=m.desc;const fallback=$("videoFallback");if(fallback)fallback.style.display="none";video.removeAttribute("controls");$("playerPanel").classList.add("open");$("playerPanel").setAttribute("aria-hidden","false");document.querySelectorAll(".memory").forEach((el,k)=>el.classList.toggle("active",k===i));video.src=m.video;video.load();video.play().catch(()=>{})}
function closePlayer(){$("playerPanel").classList.remove("open");$("playerPanel").setAttribute("aria-hidden","true");video.pause();video.removeAttribute("src");video.load();document.querySelectorAll(".memory").forEach(x=>x.classList.remove("active"));active=-1}
function markWatched(i){if(i<0||i>=memories.length)return;if(!watched.includes(i)){watched.push(i);watched.sort((a,b)=>a-b);try{localStorage.setItem("nashaVolnaWatched",JSON.stringify(watched))}catch(e){}render()}if(watched.length===memories.length&&!secretShown){secretShown=true;setTimeout(showSecret,900)}}
function showSecret(){const secret=$("secret");if(!secret)return;secret.classList.add("show");secret.setAttribute("aria-hidden","false");updateCounter()}
function updateCounter(){const start=new Date("2021-04-09T00:00:00"),ms=Math.max(0,Date.now()-start.getTime());$("days").textContent=Math.floor(ms/864e5).toLocaleString("ru-RU");$("hours").textContent=Math.floor(ms/36e5).toLocaleString("ru-RU");$("minutes").textContent=Math.floor(ms/6e4).toLocaleString("ru-RU")}
function fmt(s){s=Math.floor(s||0);return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
$("closePlayer").onclick=closePlayer;$("playBtn").onclick=()=>video.paused?video.play():video.pause();video.addEventListener("play",()=>$("playBtn").textContent="Ⅱ");video.addEventListener("pause",()=>$("playBtn").textContent="▶");video.addEventListener("timeupdate",()=>{const p=video.duration?video.currentTime/video.duration:0;$("progressBar").style.width=p*100+"%";$("playerTime").textContent=fmt(video.currentTime);$("playerDuration").textContent=fmt(video.duration)});video.addEventListener("ended",()=>{if(active>=0)markWatched(active)});video.addEventListener("error",()=>{const f=$("videoFallback");if(f)f.style.display="grid"});updateCounter();setInterval(updateCounter,30000);render();
const ctx=canvas.getContext("2d");if(!ctx)return;function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);positionMemories()}window.addEventListener("resize",resize,{passive:true});resize();
function drawOrganicLoop(x,y,rx,ry,rot,alpha,weight,phase,idx){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.beginPath();const steps=90;for(let k=0;k<=steps;k++){const a=k/steps*Math.PI*2,wobble=1+.045*Math.sin(a*3+phase+idx*.7)+.025*Math.sin(a*7-phase),px=Math.cos(a)*rx*wobble,py=Math.sin(a)*ry*(1+.035*Math.cos(a*4-phase));if(k===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.closePath();ctx.lineWidth=weight;ctx.strokeStyle=`hsla(${hue},92%,76%,${alpha})`;ctx.shadowBlur=weight>1?18:9;ctx.shadowColor=`hsla(${hue},95%,72%,${alpha*.75})`;ctx.stroke();ctx.restore()}
function drawWave(){const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;if(!w||!h){requestAnimationFrame(drawWave);return}ctx.clearRect(0,0,w,h);waveT+=.008;hue+=(targetHue-hue)*.018;const phase=waveT*1.05,mobile=w<901,centerX=w*.5,amp=Math.min(w*(mobile?.36:.30),mobile?150:430);for(let layer=0;layer<9;layer++){ctx.beginPath();for(let y=-30;y<=h+30;y+=3){const yy=y/h,drift=Math.sin(yy*7.5+waveT*.75+layer*.45)*w*(mobile?.025:.035),main=Math.sin(yy*9.2-waveT*(1.05+layer*.025))*amp,detail=Math.sin(yy*22+waveT*1.3+layer)*w*(mobile?.012:.018),x=centerX+main+drift+detail;if(y===-30)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.lineWidth=layer===0?3.1:layer<3?1.8:1;ctx.shadowBlur=layer===0?34:layer<3?18:8;ctx.shadowColor=`hsla(${hue},95%,72%,${layer===0?.72:.3})`;ctx.strokeStyle=`hsla(${hue},92%,${layer<2?75:69}%,${layer===0?.68:layer<3?.29:.12})`;ctx.stroke()}
const hr=hero.getBoundingClientRect();document.querySelectorAll(".memory").forEach((el,i)=>{const er=el.getBoundingClientRect(),x=er.left-hr.left+er.width/2,y=er.top-hr.top+er.height/2,rad=er.width/2,local=phase+i*.37;el.style.setProperty("--wave-phase",`${(Math.sin(local)*18).toFixed(2)}deg`);for(let j=0;j<3;j++){const rr=rad+7+j*5;drawOrganicLoop(x,y,rr*(1.2+j*.025),rr*(.9+j*.035),local*.34+j*.21,j===0?.52:.16,j===0?1.65:1,local,j)}for(let j=0;j<2;j++){const bx=x+Math.cos(local+j*2.8)*rad*1.72,by=y+Math.sin(local+j*2.8)*rad*1.72;ctx.beginPath();ctx.arc(bx,by,1.7+j,0,Math.PI*2);ctx.fillStyle=`hsla(${hue},95%,78%,${.28-j*.06})`;ctx.shadowBlur=8;ctx.shadowColor=`hsla(${hue},95%,72%,.45)`;ctx.fill()}});ctx.shadowBlur=0;requestAnimationFrame(drawWave)}drawWave()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();