const {test}=require('node:test'),assert=require('node:assert/strict'),f=require('../finance-core.js'),storage=require('../storage-core.js'),crm=require('../crm-core.js');
const today='2026-09-29';
const data=()=>({messages:[],tasks:[],projects:[],clients:[{id:'c',name:'Клиент'}],orders:[{id:'o',name:'Лендинг',clientId:'c',status:'В работе',amount:'100.00'}],ledger:[],memories:[],docs:[],employees:[]});
function entry(d,id,kind,amount,extra={}){return {id,...f.validate({kind,amount,orderId:'o',category:'Оплата заказа',note:'Проверка',date:'2026-09-27',...extra},d,today)};}
test('partial payments, expenses and refund produce exact balances and remaining amount',()=>{const d=data();d.ledger=[entry(d,'i','income','60.10'),entry(d,'e','expense','20.20'),entry(d,'r','refund','10.05')];const s=f.orderSummary(d,d.orders[0]);assert.equal(s.netPaid,5005);assert.equal(s.expense,2020);assert.equal(s.balance,2985);assert.equal(s.due,4995);});
test('payment precision and validation reject unsafe values, future dates and orphan orders',()=>{const d=data();assert.equal(f.cents('0,10')+f.cents('0.20'),30);for(const amount of ['0','-1','1e3','0.001','9999999999','Infinity'])assert.throws(()=>entry(d,'i','income',amount));assert.throws(()=>entry(d,'i','income','1',{date:'2026-02-30'}));assert.throws(()=>entry(d,'i','income','1',{date:'2026-10-01'}));assert.throws(()=>entry(d,'i','income','1',{orderId:''}));assert.throws(()=>entry(d,'i','income','1',{orderId:'missing'}));assert.equal(entry(d,'e','expense','1',{orderId:''}).orderId,'');});
test('reversal cancels original without deleting it; filtering uses correction date',()=>{const d=data();d.ledger=[entry(d,'i','income','40')];d.ledger.push({id:'r',...f.reverse(d,'i','Ошибка',today)});assert.equal(f.totals(d).balance,0);assert.equal(d.ledger[0].amount,'40.00');assert.equal(f.totals(d,{from:today,to:today}).balance,-4000);assert.throws(()=>f.reverse(d,'i','Повтор',today));assert.throws(()=>f.reverse(d,'r','Повтор',today));});
test('reversing expense and refund restores the correct columns',()=>{for(const kind of ['expense','refund']){const d=data();d.ledger=[entry(d,'x',kind,'12.34')];d.ledger.push({id:'r',...f.reverse(d,'x','Ошибка',today)});const s=f.totals(d);assert.equal(s.income,0);assert.equal(s.expense,0);assert.equal(s.refund,0);}});
test('cancelled and unpriced orders are excluded from remaining totals, overpayment shown separately',()=>{const d=data();d.ledger=[entry(d,'i','income','110')];assert.equal(f.orderSummary(d,d.orders[0]).overpaid,1000);assert.equal(f.portfolio(d).due,0);d.orders[0].status='Отменён';assert.equal(f.orderSummary(d,d.orders[0]).due,null);assert.equal(f.totals(d).income,11000);d.orders[0].status='В работе';d.orders[0].amount='';assert.equal(f.portfolio(d).unknown,1);});
test('CSV protects formula cells, quotes and newlines; includes only selected rows',()=>{const d=data();d.orders[0].name='=HYPERLINK("x")';d.ledger=[entry(d,'a','income','1',{note:' +SUM(1,1)\n"quoted"'}),entry(d,'b','expense','2',{date:today})];const csv=f.csv(d,{to:'2026-09-28'});assert.ok(csv.startsWith('\uFEFF'));assert.match(csv,/'=HYPERLINK/);assert.match(csv,/'\+SUM/);assert.ok(csv.includes('""quoted""'));assert.ok(!csv.includes('"b"'));});
test('financial answers use recorded sources and never mutate data',()=>{const d=data();d.ledger=[entry(d,'i','income','10')];const before=structuredClone(d);assert.match(f.answer('Экономика заказа Лендинг',d),/orders:o/);assert.match(f.answer('Сколько нам должны?',d),/90,00/);assert.deepEqual(d,before);assert.equal(f.answer('Привет',d),null);});
test('v3 backup preserves ledger and rejects tampered or repeated reversals',()=>{const d=data();d.ledger=[entry(d,'i','income','10')];d.ledger.push({id:'r',...f.reverse(d,'i','Ошибка',today)});const api=storage.open({getItem:()=>null},'x');assert.deepEqual(storage.parseBackup(api.export(d)),d);let e=JSON.parse(api.export(d));e.state.ledger[1].amount='9.00';assert.throws(()=>storage.parseBackup(JSON.stringify(e)),/обратная/);e=JSON.parse(api.export(d));e.state.ledger.push({...e.state.ledger[1],id:'r2'});assert.throws(()=>storage.parseBackup(JSON.stringify(e)),/обратная/);});
test('v1 and v2 backups migrate, invalid relationships and script object fields are rejected',()=>{const api=storage.open({getItem:()=>null},'x');for(const version of [1,2]){const e=JSON.parse(api.export(data()));e.version=version;delete e.state.ledger;if(version===1)delete e.state.orders;assert.deepEqual(storage.parseBackup(JSON.stringify(e)).ledger,[]);}const d=data();d.ledger=[entry(d,'i','income','10')];d.ledger[0].orderId='missing';assert.throws(()=>storage.parseBackup(api.export(d)));d.ledger[0].orderId='o';d.ledger[0].note={constructor:'x'};assert.throws(()=>storage.parseBackup(api.export(d)));});
test('financial records and linked documents prevent order deletion',()=>{const d=data();d.ledger=[entry(d,'i','income','10')];assert.throws(()=>crm.removeOrder(d,'o'),/финансовые/);d.ledger=[];d.docs=[{id:'doc',name:'ТЗ',orderId:'o'}];assert.throws(()=>crm.removeOrder(d,'o'),/документы/);});
