const {test}=require('node:test');const assert=require('node:assert/strict');const core=require('../storage-core.js');const search=require('../search-core.js');
const state=()=>({messages:[],tasks:[{id:'t1',title:'Оплатить счёт',status:'Новая'}],projects:[],memories:[],docs:[],clients:[],employees:[],orders:[],ledger:[]});
function store(){const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};}
test('undo survives reload; undo itself cannot be undone',()=>{const s=store(),a=core.open(s,'x'),before=state(),after=state();after.tasks=[];a.commit(after,'Удаление',before);const b=core.open(s,'x');assert.deepEqual(b.undo(),before);b.commit(b.undo(),'Отмена',after,true);assert.equal(b.canUndo(),false);assert.equal(b.history().length,2);});
test('failed write preserves history and undo',()=>{const s=store(),a=core.open(s,'x');s.setItem=()=>{throw Error('quota');};assert.throws(()=>a.commit(state(),'Fail',state()));assert.deepEqual(a.history(),[]);assert.equal(a.canUndo(),false);});
test('stale tabs cannot overwrite newer data',()=>{const s=store(),a=core.open(s,'x'),b=core.open(s,'x');a.commit(state(),'Первый',state());const before=s.getItem('x');assert.throws(()=>b.commit(state(),'Второй',state()),/другой вкладке/);assert.equal(s.getItem('x'),before);});
test('corrupt JSON is preserved and write-protected',()=>{const s=store();s.setItem('x','{broken');const a=core.open(s,'x');assert.ok(a.problem());assert.throws(()=>a.commit(state(),'Overwrite',state()));assert.equal(s.getItem('x'),'{broken');});
test('backup round trips only records and rejects duplicates, wrong versions and malformed data',()=>{const a=core.open(store(),'x'),x=state();x.workspaceToken='secret';assert.deepEqual(core.parseBackup(a.export(x)),state());assert.ok(!a.export(x).includes('secret'));const bad=JSON.parse(a.export(x));bad.state.tasks.push(bad.state.tasks[0]);assert.throws(()=>core.parseBackup(JSON.stringify(bad)),/ID/);bad.version=4;assert.throws(()=>core.parseBackup(JSON.stringify(bad)),/версии/);});
test('search finds several words across record fields and treats regex characters literally',()=>{const x=state();x.docs=[{id:'d',name:'Счёт клиента',text:'Оплатить завтра [100]'}];assert.equal(search.search(x,'оплатить счёт').length,2);assert.equal(search.search(x,'[100]')[0].id,'d');assert.deepEqual(search.search(x,'   '),[]);assert.deepEqual(search.search(x,'.*'),[]);});
